# Generated by Django 3.2.6 on 2021-09-11 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillprerequisite',
            name='skill',
        ),
        migrations.DeleteModel(
            name='SkillTree',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.DeleteModel(
            name='SkillPrerequisite',
        ),
    ]
